import type { Project, Experience, Metric } from '@/types'

export const projects: Project[] = [
  {
    id: 'capture-call',
    title: 'Enterprise Calling System',
    tagline: 'Enterprise Call Management Platform',
    problem: 'Legacy call center infrastructure struggled with real-time session tracking, causing dropped connections and unreliable data logging for 500+ concurrent agents.',
    solution: 'Architected a full-stack MERN platform with WebSocket-based real-time event broadcasting, optimized MongoDB schemas, and a React TypeScript dashboard with live analytics.',
    impact: '99.8% event delivery reliability, 35% faster dashboard queries, seamless handling of 500+ concurrent call sessions.',
    tech: ['React.js', 'TypeScript', 'Node.js', 'MongoDB', 'WebSocket', 'Express.js'],
    category: ['frontend', 'backend', 'database'],
    github: 'https://github.com/AlienAlien369',
    metrics: [
      { label: 'Concurrent Sessions', value: '500+' },
      { label: 'Event Delivery', value: '99.8%' },
      { label: 'Query Speed', value: '+35%' },
    ],
    featured: true,
  },
  {
    id: 'library-system',
    title: 'Library Management System',
    tagline: 'Full-Stack MERN with Advanced Search',
    problem: 'Managing 10,000+ book records with complex multi-criteria search and role-based workflows for librarians and members was slow and prone to data inconsistency.',
    solution: 'Built a full-stack MERN application with JWT-based RBAC, MongoDB aggregation pipelines for advanced search, and a clean React interface with real-time availability updates.',
    impact: '50% improvement in search efficiency, support for 10,000+ records, zero unauthorized access incidents.',
    tech: ['React.js', 'Node.js', 'MongoDB', 'JWT', 'Express.js', 'TypeScript'],
    category: ['frontend', 'backend', 'database'],
    github: 'https://github.com/AlienAlien369',
    metrics: [
      { label: 'Book Records', value: '10K+' },
      { label: 'Search Speed', value: '+50%' },
      { label: 'Auth Issues', value: '0' },
    ],
    featured: true,
  },
  {
    id: 'enterprise-api',
    title: 'Enterprise REST API Gateway',
    tagline: 'Scalable .NET Core Microservices',
    problem: 'Monolithic API architecture creating bottlenecks under load, with no rate limiting, poor observability, and inconsistent authentication across 20+ endpoints.',
    solution: 'Redesigned with ASP.NET Core, implementing JWT/OAuth 2.0 with RBAC, rate-limiting middleware, centralized structured logging, IIS reverse proxy, and CI/CD pipeline.',
    impact: '30% API latency reduction, 45% faster SQL queries, 99.9% uptime, elimination of all unauthorized access incidents.',
    tech: ['ASP.NET Core', 'SQL Server', 'JWT', 'OAuth 2.0', 'IIS', 'Azure DevOps'],
    category: ['backend', 'database', 'devops'],
    github: 'https://github.com/AlienAlien369',
    metrics: [
      { label: 'Latency Drop', value: '-30%' },
      { label: 'Query Speed', value: '+45%' },
      { label: 'Uptime', value: '99.9%' },
    ],
    featured: true,
  },
  {
    id: 'iot-tracking',
    title: 'IoT Location Intelligence',
    tagline: 'Real-Time Geospatial Data Pipeline',
    problem: 'Processing 1,000+ real-time location events daily from IoT fleet devices with no reliable pipeline, causing data loss and delayed dashboard updates.',
    solution: 'Built event-driven data pipeline integrating Google Maps API with ASP.NET Core backend, Redis caching layer, and React dashboard with live map visualization.',
    impact: '1,000+ events/day processed reliably, sub-second map updates, comprehensive fleet visibility dashboard.',
    tech: ['ASP.NET Core', 'Google Maps API', 'Redis', 'React.js', 'SQL Server', 'IoT'],
    category: ['backend', 'frontend', 'devops'],
    github: 'https://github.com/AlienAlien369',
    metrics: [
      { label: 'Events/Day', value: '1K+' },
      { label: 'Update Latency', value: '<1s' },
      { label: 'Data Loss', value: '0%' },
    ],
  },
  {
    id: 'payment-platform',
    title: 'Multi-Gateway Payment Platform',
    tagline: 'Resilient Payment Integration Layer',
    problem: 'Fragile payment integrations across 3+ gateways with no retry logic, poor error visibility, and direct coupling causing cascading failures on gateway downtime.',
    solution: 'Engineered abstraction layer in ASP.NET MVC with Polly resilience patterns, structured logging, webhook handling, and a unified API interface across all payment providers.',
    impact: '500+ daily transactions, zero payment data loss, 40% reduction in gateway-related errors.',
    tech: ['ASP.NET MVC', 'C#', 'Polly', 'SQL Server', 'REST APIs', 'Webhook'],
    category: ['backend', 'database'],
    github: 'https://github.com/AlienAlien369',
    metrics: [
      { label: 'Daily Transactions', value: '500+' },
      { label: 'Error Reduction', value: '-40%' },
      { label: 'Data Loss', value: '0' },
    ],
  },
  {
    id: 'media-platform',
    title: 'Cloud Media Platform',
    tagline: 'Cloudinary-Powered Asset Management',
    problem: 'Manual media management with no optimization pipeline, oversized assets degrading performance and storage costs scaling uncontrollably.',
    solution: 'Integrated Cloudinary with automatic transformation pipelines, lazy loading, WebP conversion, responsive srcsets, and a React-based media management dashboard.',
    impact: '60% reduction in average image size, 40% faster page loads, scalable CDN delivery.',
    tech: ['React.js', 'Next.js', 'Cloudinary', 'Node.js', 'TypeScript', 'CDN'],
    category: ['frontend', 'devops'],
    github: 'https://github.com/AlienAlien369',
    metrics: [
      { label: 'Image Size', value: '-60%' },
      { label: 'Page Speed', value: '+40%' },
      { label: 'CDN Hit Rate', value: '98%' },
    ],
  },
]

export const experiences: Experience[] = [
  {
    company: 'Binary Semantics',
    role: 'SDE – Full Stack',
    period: 'Nov 2024 – Present',
    location: 'Gurugram, India',
    type: 'fulltime',
    highlights: [
      'Led end-to-end development of 30+ enterprise web applications serving 5,000+ active users',
      'Engineered 25+ RESTful APIs and refactored 40+ SQL Server stored procedures — reducing query time by 45% and API latency by 30%',
      'Designed JWT/OAuth 2.0 authentication with RBAC and rate-limiting middleware, achieving zero unauthorized access incidents',
      'Configured IIS-based reverse proxy to securely expose 10+ internal services with 99.9% uptime',
      'Integrated Google Maps APIs and IoT data pipelines processing 1,000+ real-time location events daily',
      'Implemented 80% unit test coverage with centralized logging and CI workflows',
    ],
    tech: ['ASP.NET Core', 'React.js', 'TypeScript', 'SQL Server', 'JWT', 'IIS', 'Azure DevOps'],
    color: '#00d9ff',
  },
  {
    company: 'Acxiom Consulting',
    role: '.NET Developer',
    period: 'Feb 2024 – Oct 2024',
    location: 'Gurugram, India',
    type: 'fulltime',
    highlights: [
      'Contributed to 20+ ASP.NET MVC modules across 3 enterprise projects',
      'Optimized 25+ T-SQL stored procedures with indexing and CTEs — 40% performance improvement',
      'Built 15+ backend APIs handling 500+ daily transactional requests with structured logging',
      'Integrated 5+ third-party services including payment gateways and SMS APIs',
    ],
    tech: ['ASP.NET MVC', 'C#', 'T-SQL', 'SQL Server', 'REST APIs'],
    color: '#3b82f6',
  },
]

export const metrics: Metric[] = [
  { label: 'Enterprise Apps Delivered', value: '30', suffix: '+', description: 'Production-grade web applications shipped', icon: '🏗' },
  { label: 'APIs Engineered', value: '25', suffix: '+', description: 'RESTful APIs with structured logging', icon: '⚡' },
  { label: 'Query Optimization', value: '45', suffix: '%', description: 'Average SQL execution improvement', icon: '🔥' },
  { label: 'System Uptime', value: '99.9', suffix: '%', description: 'Production reliability achieved', icon: '🎯' },
  { label: 'Active Users Served', value: '5K', suffix: '+', description: 'Daily active users across systems', icon: '👥' },
  { label: 'Test Coverage', value: '80', suffix: '%', description: 'Unit test coverage maintained', icon: '✅' },
]

export const techCategories = {
  frontend: [
    { name: 'React.js', color: '#61DAFB', icon: '⚛' },
    { name: 'Next.js', color: '#ffffff', icon: '▲' },
    { name: 'TypeScript', color: '#3178C6', icon: 'TS' },
    { name: 'Tailwind CSS', color: '#06B6D4', icon: '🎨' },
    { name: 'Framer Motion', color: '#FF0066', icon: '✦' },
    { name: 'HTML/CSS', color: '#E34F26', icon: '🌐' },
  ],
  backend: [
    { name: 'ASP.NET Core', color: '#512BD4', icon: '.N' },
    { name: 'C#', color: '#512BD4', icon: 'C#' },
    { name: 'Node.js', color: '#339933', icon: '⬡' },
    { name: 'Express.js', color: '#ffffff', icon: '🚀' },
    { name: 'REST APIs', color: '#FF6B6B', icon: '🔌' },
  ],
  database: [
    { name: 'SQL Server', color: '#CC2927', icon: '🗄' },
    { name: 'MongoDB', color: '#47A248', icon: '🍃' },
    { name: 'PostgreSQL', color: '#4169E1', icon: '🐘' },
    { name: 'Redis', color: '#DC382D', icon: '⚡' },
  ],
  devops: [
    { name: 'Azure DevOps', color: '#0078D4', icon: '☁' },
    { name: 'Docker', color: '#2496ED', icon: '🐳' },
    { name: 'Git', color: '#F05032', icon: '⎇' },
    { name: 'IIS', color: '#009639', icon: '🔄' },
    { name: 'Cloudinary', color: '#3448C5', icon: '🖼' },
    { name: 'CI/CD', color: '#00d9ff', icon: '♾' },
  ],
}
